### PR TITLE
updated gpt system content to respond based on negative sentiment

### LINKED ISSUE #13: Add text sentiment analysis to Dialogue Flow

### PR DESCRIPTION
**Pull request by vnoelifant**
I just changed the GPT system content and it was able to reply back with a joke when detecting negative sentiment! Pretty powerful. Terminal output is below.  I'll make a little video later. @Zaubeerer 

```
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Something Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Something Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Something Said
Nothing Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Recording Complete
Saving speech audio to file
Transcribing audio....

User Speech Text: I feel terrible today  

Conversation Log:  [{'role': 'system', 'content': 'You are a helpful, friendly assistant.If you detect              negative sentiment from the user, reply with a joke.'}, {'role': 'user', 'content': 'I feel terrible today '}, {'role': 'assistant', 'content': 'Why don’t scientists trust atoms? Because they make up everything. I hope this joke made you smile and feel a bit better today.'}]
GPT Response Message: Why don’t scientists trust atoms? Because they make up everything. I hope this joke made you smile and feel a bit better today.

13:09:20.632               robot.Robot WARNING  No serial number or name provided. Automatically selecting 0dd195ec      
13:09:20.634     connection.Connection    INFO  Connecting to 10.0.0.106:443 for Vector-V9Z6 using C:\Users\veron\.anki_vector\Vector-V9Z6-0dd195ec.cert
13:09:21.247     connection.Connection    INFO  BehaviorControl control_granted_response { }
13:09:21.933       events.EventHandler WARNING  Unknown Event type
13:09:22.324       events.EventHandler WARNING  Unknown Event type
13:09:22.795       events.EventHandler WARNING  Unknown Event type
13:09:23.354       events.EventHandler WARNING  Unknown Event type
13:09:23.817       events.EventHandler WARNING  Unknown Event type
13:09:24.241       events.EventHandler WARNING  Unknown Event type
13:09:24.656       events.EventHandler WARNING  Unknown Event type
13:09:25.571       events.EventHandler WARNING  Unknown Event type
13:09:25.628       events.EventHandler WARNING  Unknown Event type
13:09:26.117       events.EventHandler WARNING  Unknown Event type
13:09:26.591       events.EventHandler WARNING  Unknown Event type
13:09:26.947       events.EventHandler WARNING  Unknown Event type
13:09:27.485       events.EventHandler WARNING  Unknown Event type
13:09:27.955       events.EventHandler WARNING  Unknown Event type
13:09:28.380       events.EventHandler WARNING  Unknown Event type
13:09:28.915       events.EventHandler WARNING  Unknown Event type
13:09:29.399       events.EventHandler WARNING  Unknown Event type
13:09:29.875       events.EventHandler WARNING  Unknown Event type
13:09:30.420       events.EventHandler WARNING  Unknown Event type
13:09:30.898       events.EventHandler WARNING  Unknown Event type
13:09:31.434       events.EventHandler WARNING  Unknown Event type
13:09:31.860       events.EventHandler WARNING  Unknown Event type
13:09:32.275       events.EventHandler WARNING  Unknown Event type
13:09:32.761       events.EventHandler WARNING  Unknown Event type
13:09:33.176       events.EventHandler WARNING  Unknown Event type
13:09:33.593       events.EventHandler WARNING  Unknown Event type
13:09:34.017       events.EventHandler WARNING  Unknown Event type
13:09:34.560       events.EventHandler WARNING  Unknown Event type
13:09:34.977       events.EventHandler WARNING  Unknown Event type
13:09:35.403       events.EventHandler WARNING  Unknown Event type
13:09:36.102       events.EventHandler WARNING  Unknown Event type
Starting recording process
Please say something to the microphone

Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Recording Complete
Saving speech audio to file
Transcribing audio....

User Speech Text: thank you for that  

Conversation Log:  [{'role': 'system', 'content': 'You are a helpful, friendly assistant.If you detect              negative sentiment from the user, reply with a joke.'}, {'role': 'user', 'content': 'I feel terrible today '}, {'role': 'assistant', 'content': 'Why don’t scientists trust atoms? Because they make up everything. I hope this joke made you smile and feel a bit better today.'}, {'role': 'user', 'content': 'thank you for that '}, {'role': 'assistant', 'content': "You are welcome! Remember, laughter is the best medicine. If there's anything else I can help you with, please don't hesitate to ask!"}]
GPT Response Message: You are welcome! Remember, laughter is the best medicine. If there's anything else I can help you with, please don't hesitate to ask!

13:09:45.402               robot.Robot WARNING  No serial number or name provided. Automatically selecting 0dd195ec      
13:09:45.404     connection.Connection    INFO  Connecting to 10.0.0.106:443 for Vector-V9Z6 using C:\Users\veron\.anki_vector\Vector-V9Z6-0dd195ec.cert
13:09:45.915     connection.Connection    INFO  BehaviorControl control_granted_response { }
13:09:46.678       events.EventHandler WARNING  Unknown Event type
13:09:47.172       events.EventHandler WARNING  Unknown Event type
13:09:47.639       events.EventHandler WARNING  Unknown Event type
13:09:48.116       events.EventHandler WARNING  Unknown Event type
13:09:48.716       events.EventHandler WARNING  Unknown Event type
13:09:49.139       events.EventHandler WARNING  Unknown Event type
13:09:49.680       events.EventHandler WARNING  Unknown Event type
13:09:50.096       events.EventHandler WARNING  Unknown Event type
13:09:50.701       events.EventHandler WARNING  Unknown Event type
13:09:51.251       events.EventHandler WARNING  Unknown Event type
13:09:51.782       events.EventHandler WARNING  Unknown Event type
13:09:52.322       events.EventHandler WARNING  Unknown Event type
13:09:52.923       events.EventHandler WARNING  Unknown Event type
13:09:53.336       events.EventHandler WARNING  Unknown Event type
13:09:53.759       events.EventHandler WARNING  Unknown Event type
13:09:54.234       events.EventHandler WARNING  Unknown Event type
13:09:54.778       events.EventHandler WARNING  Unknown Event type
13:09:55.257       events.EventHandler WARNING  Unknown Event type
13:09:55.680       events.EventHandler WARNING  Unknown Event type
13:09:56.099       events.EventHandler WARNING  Unknown Event type
13:09:56.636       events.EventHandler WARNING  Unknown Event type
13:09:57.056       events.EventHandler WARNING  Unknown Event type
13:09:57.478       events.EventHandler WARNING  Unknown Event type
13:09:58.015       events.EventHandler WARNING  Unknown Event type
13:09:58.555       events.EventHandler WARNING  Unknown Event type
13:09:59.038       events.EventHandler WARNING  Unknown Event type
Starting recording process
Please say something to the microphone

Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Something Said
Nothing Said
Something Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Nothing Said
Recording Complete
Saving speech audio to file

```

### CODE REVIEW

**Comment by vnoelifant** [comment]
Here is a video @Zaubeerer 
https://youtu.be/aw8tuT5BsDM

**Comment by vnoelifant** [comment]
Couple of questions on the EXIT_CONDITION to end the program by saying "exit."

1) Do you think the EXIT_CONDITION constant in [cli.py](https://github.com/vnoelifant/cozmo-companion/blob/vector-gpt-sentiment/src/cozmo_companion/cli.py) should live in [constants.py](https://github.com/vnoelifant/cozmo-companion/blob/main/src/cozmo_companion/constants.py)? @Zaubeerer 

2) Which do you think would be a better if statement expression, or does it really matter?
 ```
if EXIT_CONDITION in speech_text.strip().lower():
```
```
if speech_text.strip().lower() in EXIT_CONDITION:
```

**Review by Zaubeerer — APPROVED** [review]
Wow, such a simple and powerful prompt!

**Comment by Zaubeerer** [comment]
> Couple of questions on the EXIT_CONDITION to end the program by saying "exit."
> 
> 1. Do you think the EXIT_CONDITION constant in [cli.py](https://github.com/vnoelifant/cozmo-companion/blob/vector-gpt-sentiment/src/cozmo_companion/cli.py) should live in [constants.py](https://github.com/vnoelifant/cozmo-companion/blob/main/src/cozmo_companion/constants.py)? @Zaubeerer
> 2. Which do you think would be a better if statement expression, or does it really matter?
> 
> ```
> if EXIT_CONDITION in speech_text.strip().lower():
> ```
> 
> ```
> if speech_text.strip().lower() in EXIT_CONDITION:
> ```

Please make these comments directly next to the code, as I will do below:

**Comment by Zaubeerer** [comment]
Ah, just saw that you did not edit those files in this PR, so answering your questions here:

1. no, I think that would be overkill at this point, because that constant is only relevant to this function, isn't it?
2. Actually, the second one would not work, I guess

**Comment by vnoelifant** [comment]
> Ah, just saw that you did not edit those files in this PR, so answering your questions here:
> 
> 1. no, I think that would be overkill at this point, because that constant is only relevant to this function, isn't it?
> 2. Actually, the second one would not work, I guess

I believe so on number 1. It seems more pertinent to the overall "main" function of getting to converse with GPT. Ah, I actually always wondered about how to make the code inline comments. I finally figured about about that mysterious blue plus sign. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request. I will definitely be using this. I do wonder if there is a way I can inline code comment to code that was not changed from a PR.

**Comment by Zaubeerer** [comment]
You can comment directly on the branches I think, but it is much less intuitive.

So, sometimes it is easiest to make a comment or the change you think of such that you have a miny PR with just that change ;-)

**Comment by vnoelifant** [comment]
> You can comment directly on the branches I think, but it is much less intuitive.
> 
> So, sometimes it is easiest to make a comment or the change you think of such that you have a miny PR with just that change ;-)

That makes sense. Thanks!

**Pull request merged**
